/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package trabalhoindividual.view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Tarefa;
import model.dao.TarefaDAO;

/**
 *
 * @author yanma
 */
public class JanelaTarefa extends javax.swing.JInternalFrame {

    /**
     * Creates new form JanelaTarefa
     */
    public JanelaTarefa() {
        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) TabelaTarefa.getModel();
        TabelaTarefa.setRowSorter(new TableRowSorter(modelo));

        readJTable();
    }

    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaTarefa.getModel();
        modelo.setNumRows(0);
        TarefaDAO tdao = new TarefaDAO();
        for (Tarefa t : tdao.read()) {
            modelo.addRow(new Object[]{
                t.getId(),
                t.getEstado(),
                t.getImportancia(),
                t.getNome(),
                t.getDescricao(),
                t.getTipo(),
                t.getDatafinal()
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Gravar = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        CBTipo = new javax.swing.JComboBox<>();
        CBImportancia = new javax.swing.JComboBox<>();
        FtxtData = new javax.swing.JFormattedTextField();
        CBEstado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaTarefa = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setTitle("Janela de Gerenciamento de Tarefas");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Nome");

        jLabel2.setText("Tipo");

        jLabel3.setText("Descrição");

        jLabel4.setText("Importância");

        jLabel5.setText("Data Final");

        Gravar.setText("Gravar");
        Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GravarActionPerformed(evt);
            }
        });

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        CBTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Trabalho", "Estudo", "Saúde", "Casa" }));

        CBImportancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "1", "2", "3", "4", "5" }));

        try {
            FtxtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FtxtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FtxtDataActionPerformed(evt);
            }
        });

        CBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não Concluido", "Concluido" }));

        jLabel6.setText("Estado");

        txtDescricao.setColumns(20);
        txtDescricao.setLineWrap(true);
        txtDescricao.setRows(5);
        txtDescricao.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtDescricao);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FtxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(65, 65, 65))
                                        .addComponent(CBImportancia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CBEstado, 0, 117, Short.MAX_VALUE))
                                    .addGap(3, 3, 3))
                                .addComponent(txtNome))
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(68, 68, 68)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Gravar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBImportancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FtxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gravar)
                            .addComponent(Alterar)
                            .addComponent(Excluir))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        TabelaTarefa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Estado", "Importância", "Nome", "Descrição", "Tipo", "Data Final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaTarefaMouseClicked(evt);
            }
        });
        TabelaTarefa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TabelaTarefaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaTarefa);
        if (TabelaTarefa.getColumnModel().getColumnCount() > 0) {
            TabelaTarefa.getColumnModel().getColumn(0).setMinWidth(0);
            TabelaTarefa.getColumnModel().getColumn(0).setPreferredWidth(0);
            TabelaTarefa.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void FtxtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FtxtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FtxtDataActionPerformed

    private void GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GravarActionPerformed
        // TODO add your handling code here:
        
        
        Tarefa t = new Tarefa();
        TarefaDAO dao = new TarefaDAO();
        t.setEstado((String) CBEstado.getSelectedItem());
        t.setImportancia((String) CBImportancia.getSelectedItem());
        t.setNome(txtNome.getText());
        t.setDescricao(txtDescricao.getText());
        t.setTipo((String) CBTipo.getSelectedItem());
        t.setDatafinal(FtxtData.getText());
        dao.create(t);
        
        txtNome.setText("");
        txtDescricao.setText("");
        CBTipo.setSelectedItem("Selecionar");
        CBImportancia.setSelectedItem("Selecionar");
        CBEstado.setSelectedItem("Selecionar");
        FtxtData.setText("");
        txtNome.requestFocus();

        readJTable();

        //DefaultTableModel dtmTarefas = (DefaultTableModel)TabelaTarefa.getModel();
        //Object[] dados = {CBImportancia.getSelectedItem(),txtNome.getText(),txtDescricao.getText(),CBTipo.getSelectedItem(),FtxtData.getText()};
        //dtmTarefas.addRow(dados);

    }//GEN-LAST:event_GravarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        // TODO add your handling code here:

        if (TabelaTarefa.getSelectedRow() != -1) {
            
            Tarefa t = new Tarefa();
            TarefaDAO dao = new TarefaDAO();

            t.setId((int)TabelaTarefa.getValueAt(TabelaTarefa.getSelectedRow(), 0));
            dao.delete(t);

            txtNome.setText("");
            txtDescricao.setText("");
            CBTipo.setSelectedItem("Selecionar");
            CBImportancia.setSelectedItem("Selecionar");
            CBEstado.setSelectedItem("Selecionar");
            FtxtData.setText("");
            txtNome.requestFocus();

            readJTable();
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma Tarefa para excluir.");
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        // TODO add your handling code here:

        if (TabelaTarefa.getSelectedRow() != -1) {

            Tarefa t = new Tarefa();
            TarefaDAO dao = new TarefaDAO();
            t.setEstado((String) CBEstado.getSelectedItem());
            t.setImportancia((String) CBImportancia.getSelectedItem());
            t.setNome(txtNome.getText());
            t.setDescricao(txtDescricao.getText());
            t.setTipo((String) CBTipo.getSelectedItem());
            t.setDatafinal(FtxtData.getText());
            t.setId((int)TabelaTarefa.getValueAt(TabelaTarefa.getSelectedRow(), 0));
            dao.update(t);

            txtNome.setText("");
            txtDescricao.setText("");
            CBTipo.setSelectedItem("Selecionar");
            CBImportancia.setSelectedItem("Selecionar");
            CBEstado.setSelectedItem("Selecionar");
            FtxtData.setText("");
            txtNome.requestFocus();

            readJTable();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma Tarefa para Alterar.");
        }

    }//GEN-LAST:event_AlterarActionPerformed

    private void TabelaTarefaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaTarefaMouseClicked
        // TODO add your handling code here:

        if (TabelaTarefa.getSelectedRow() != -1) {

            CBEstado.setSelectedItem(TabelaTarefa.getValueAt(TabelaTarefa.getSelectedRow(), 1).toString());
            CBImportancia.setSelectedItem(TabelaTarefa.getValueAt(TabelaTarefa.getSelectedRow(), 2).toString());
            txtNome.setText(TabelaTarefa.getValueAt(TabelaTarefa.getSelectedRow(), 3).toString());
            txtDescricao.setText(TabelaTarefa.getValueAt(TabelaTarefa.getSelectedRow(), 4).toString());
            CBTipo.setSelectedItem(TabelaTarefa.getValueAt(TabelaTarefa.getSelectedRow(), 5).toString());
            FtxtData.setText(TabelaTarefa.getValueAt(TabelaTarefa.getSelectedRow(), 6).toString());

        }

    }//GEN-LAST:event_TabelaTarefaMouseClicked

    private void TabelaTarefaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaTarefaKeyReleased
        // TODO add your handling code here:

        if (TabelaTarefa.getSelectedRow() != -1) {

            CBEstado.setSelectedItem(TabelaTarefa.getValueAt(TabelaTarefa.getSelectedRow(), 1).toString());
            CBImportancia.setSelectedItem(TabelaTarefa.getValueAt(TabelaTarefa.getSelectedRow(), 2).toString());
            txtNome.setText(TabelaTarefa.getValueAt(TabelaTarefa.getSelectedRow(), 3).toString());
            txtDescricao.setText(TabelaTarefa.getValueAt(TabelaTarefa.getSelectedRow(), 4).toString());
            CBTipo.setSelectedItem(TabelaTarefa.getValueAt(TabelaTarefa.getSelectedRow(), 5).toString());
            FtxtData.setText(TabelaTarefa.getValueAt(TabelaTarefa.getSelectedRow(), 6).toString());

        }

    }//GEN-LAST:event_TabelaTarefaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JComboBox<String> CBEstado;
    private javax.swing.JComboBox<String> CBImportancia;
    private javax.swing.JComboBox<String> CBTipo;
    private javax.swing.JButton Excluir;
    private javax.swing.JFormattedTextField FtxtData;
    private javax.swing.JButton Gravar;
    private javax.swing.JTable TabelaTarefa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
